Projet_Django/urls.py
from django.contrib import admin, auth
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Jeu',include('jeu.urls'),name='Jeu'),
    path('game/', include('game.urls', namespace='game')),
    path('',include('Student_Help.urls'),name='Student_Help'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/',auth_views.LoginView.as_view(template_name='registration/login.html'), name = 'login'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/',auth_views.LoginView.as_view(template_name='registration/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name = 'logout'),


    
    
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

Student_Help/urls.py
from django.urls import path
from . import views
from .views import UserEditView,ModifierPost,SupprimerPost,ModifierComment,SupprimerComment,ModifierCommentl,SupprimerCommentl

app_name = 'Student_Help'

urlpatterns = [
    path('', views.ind, name="ind"),
    path('ajoutRec/', views.ajoutRec, name="ajoutRec"),
    path('rec/', views.mesRec, name='rec'),
    path('list_posts/', views.list_posts, name='poste'),
    path('ajoutLogement/', views.ajoutLogement, name='ajoutLogement'),
    path('ajoutTransport/', views.ajoutTransport, name='ajoutTransport'),
    path('ajoutStage/', views.ajoutStage, name='ajoutStage'),
    path('ajoutEvenement/', views.ajoutEvenement, name='ajoutEvenement'),
    path('register/',views.register, name = 'register'),
    path('list_Enseignant/',views.list_Enseignant , name="list_Enseignant"),
    path('plan/',views.plan , name="plan"),
    path('organigramme/',views.org , name="org"),
    path('clubIset/',views.clubIset , name="clubIset"),
    path('galerie/',views.galerie , name="galerie"),
    path('contact/',views.AjoutContact , name="contact"),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.user_login, name='login'),
    path('notif/', views.notification_list, name='notif'),
    path('post/', views.post, name='post'),
    path('recpost/', views.recPost, name='recpost'),
    path('logPost/', views.logPost, name='logPost'),
    path('logTrans/', views.logTrans, name='logTrans'),
    path('stgPost/', views.stgPost, name='stgPost'),
    path('evPost/', views.evPost, name='evPost'),
    path("edit-profile/", UserEditView.as_view(), name="edit_profile"),
    path('<int:pk>/modifier/', ModifierPost.as_view(), name='modifier_post'),  
    path('<int:pk>/supprimer/', SupprimerPost.as_view(), name='supprimer_post'),
    path('recommandation/<int:recommandation_id>/commentaire/ajouter/', views.ajouter_commentaire, name='ajouter_commentaire'),
    path('like/recommandation/<int:recommandation_id>/', views.like_recommandation, name='like_recommandation'),
    path('recommandation/<int:recommandation_id>/commentaires/creer/', views.creer_commentaire, name='creer_commentaire'),
    path('send/',views.send , name='send'),
    path('like/logement/<int:logement_id>/', views.like_logement, name='like_logement'),
    path('like/stage/<int:stage_id>/', views.like_stage, name='like_stage'),
    path('like/transport/<int:transport_id>/', views.like_transport, name='like_transport'),
    path('like/event/<int:evenement_id>/', views.like_event, name='like_event'),

    path('list_comments/<int:publication_id>/', views.list_comments, name='list_comments'),
    path('<int:pk>/modifiercomment/', ModifierComment.as_view(), name='Modifier_comment'),  
    path('<int:pk>/supprimercomment/', SupprimerComment.as_view(), name='Supprimer_comment'),

    path('logement/<int:logement_id>/commentaires/creer/', views.creer_commentairel, name='creer_commentairel'),
    path('comments_logement/<int:publication_id>/', views.comments_l, name='comments_logement'),
    path('<int:pk>/modifiercommentl/', ModifierCommentl.as_view(), name='Modifier_commentl'),  
    path('<int:pk>/supprimercommentl/', SupprimerCommentl.as_view(), name='Supprimer_commentl'),

    path('transport/<int:transport_id>/commentaires/creer/', views.creer_commentairet, name='creer_commentairet'),
    path('comments_transport/<int:publication_id>/', views.comments_t, name='comments_transport'),

    path('stage/<int:stage_id>/commentaires/creer/', views.creer_commentaires, name='creer_commentaires'),
    path('comments_stage/<int:publication_id>/', views.comments_s, name='comments_stage'),

    path('event/<int:evenement_id>/commentaires/creer/', views.creer_commentairee, name='creer_commentairee'),
    path('comments_event/<int:publication_id>/', views.comments_e, name='comments_event'),

    path('notif/', views.notification_l, name='notif'),
    path('notif/', views.notification_s, name='notifs'),
    path('notif/', views.notification_t, name='notif'),
    path('notif/', views.notification_e, name='notif'),
    path('notif/', views.notification_cr, name='notif'),


    path('inbox/', views.inbox, name='inbox'),
    path('sendMessage/', views.send_message, name='send_message'),
    path('list_message/', views.list_message, name='list_message'),

    path('invitation-sent/', views.invitation_sent, name='invitation_sent'),
    path('invite_list/', views.invite_list, name='invite_list'),
    path('invite-user/<str:username>/', views.invite_user, name='invite_user'),

    path('invitations/', views.invitation_list, name='invitation_list'),
    path('invitations/<int:invitation_id>/accept/', views.accept_invitation, name='accept_invitation'),
    path('invitations/<int:invitation_id>/reject/', views.reject_invitation, name='reject_invitation'),

    path('friends/', views.view_friends, name='view_friends'),


path('reserver/<int:logement_id>/', views.reserver_logement, name='reserver_logement'),

path('list_posts/<int:logement_id>/', views.list_postsRes, name='LogRes'),
path('sendMailEns/<str:enseignant_email>/', views.send_email_to_enseignant, name='send_email_to_enseignant')

]

game/urls.py
from django.urls import path ,include
#from django.conf.urls import url
from . import views

app_name = 'game'

urlpatterns = [
    path('', views.index, name='index'),
    path('aurevoir/', views.aurevoir, name='aurevoir')
]

jeu/urls.py
from django.urls import path
from . import views
app_name = 'jeu'
urlpatterns = [
    path('', views.home, name='home'),
    path('game/', views.game, name='game'),
]

Student_Help/views.py
from django.shortcuts import render 
from django.http import HttpResponse
from .forms import RecommandationForm ,PosteForm,LogementForm , StageForm , EvènementForm , TransportForm, ContactForm,EditProfileForm,LikeForm
from django.shortcuts import HttpResponseRedirect
from .models import Reservation,FriendList,Notificationcr,Message,Invitation, Notificatione,  Notificationt, Notifications, Notificationl,Commentairee, Commentaires ,Commentairet, Commentairel, LikeEvent ,LikeTransport , LikeStage,Likelogement,User, Contact,Recommandation, Logement,Notification, Transport, Stage, EvenClub,Enseignant,Evènement,Poste,Like,Commentaire
from django.shortcuts import redirect
from .forms import  UserCreationForm ,LoginForm,UserRegistrationForm,CommentaireForm
from django.contrib.auth import login, authenticate , logout
from django.contrib.auth.models import User
from django.http import HttpResponseBadRequest
from django.contrib import messages
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import UpdateView,DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.conf import settings
from django.http import HttpResponseBadRequest
from django.utils import timezone
from django.urls import reverse
from django.utils.crypto import get_random_string
from django.contrib.auth.models import User

@login_required
def list_message(request):
    # Récupérez tous les utilisateurs Django non connectés
    users = User.objects.exclude(pk=request.user.pk)# Passez les utilisateurs à votre modèle HTML
    return render(request, 'Student_Help/message.html', {'users': users})



@login_required
def invite_list(request):
    # Récupérer la liste d'amis de l'utilisateur connecté
    friend_list = FriendList.objects.get(user=request.user)
    friends = friend_list.friends.all()

    # Exclure l'utilisateur connecté et les amis de la liste des utilisateurs
    users = User.objects.exclude(pk=request.user.pk).exclude(pk__in=friends)

    # Passez les utilisateurs à votre modèle HTML
    return render(request, 'Student_Help/invite_list.html', {'users': users})


@login_required
def inbox(request):
    messages = Message.objects.all()
    users =User.objects.exclude(pk=request.user.pk)
    return render(request, 'Student_Help/message.html', {'messages': messages,'users':users})


@login_required
def send_message(request):
    if request.method == 'POST':
        body = request.POST.get('message_body')

        if body:
            sender = request.user
            
            # Créer un message avec l'utilisateur connecté comme expéditeur
            Message.objects.create(
                sender=sender,
                subject="",
                body=body,
                timestamp=timezone.now(),
            )
            
            return redirect('Student_Help:inbox')
        else:
            return HttpResponseBadRequest("Le champ du message est vide")
    
    return render(request, 'Student_Help/message.html')






def notification_list(request):
    # Récupérer toutes les notifications de l'utilisateur connecté
    notifications = Notification.objects.filter(user=request.user).order_by('-timestamp')

    return render(request, 'Student_Help/notif.html', {'notifications': notifications })

def notification_l(request):
    # Récupérer toutes les notifications de l'utilisateur connecté
    notifications = Notificationl.objects.filter(user=request.user).order_by('-timestamp')

    return render(request, 'Student_Help/notif.html', {'notifications': notifications })

def notification_s(request):
    # Récupérer toutes les notifications de l'utilisateur connecté
    notificationst = Notifications.objects.filter(user=request.user).order_by('-timestamp')

    return render(request, 'Student_Help/notif.html', {'notificationst': notificationst })

def notification_t(request):
    # Récupérer toutes les notifications de l'utilisateur connecté
    notifications = Notificationt.objects.filter(user=request.user).order_by('-timestamp')

    return render(request, 'Student_Help/notif.html', {'notifications': notifications })

def notification_e(request):
    # Récupérer toutes les notifications de l'utilisateur connecté
    notifications = Notificatione.objects.filter(user=request.user).order_by('-timestamp')

    return render(request, 'Student_Help/notif.html', {'notifications': notifications })


def notification_cr(request):
    # Récupérer toutes les notifications de l'utilisateur connecté
    notifications = Notificationcr.objects.filter(user=request.user).order_by('-timestamp')

    return render(request, 'Student_Help/notif.html', {'notifications': notifications })

@login_required
def like_recommandation(request, recommandation_id):
    if request.method == 'POST':
        recommandation = get_object_or_404(Recommandation, pk=recommandation_id)
        like, created = Like.objects.get_or_create(user=request.user, recommandation=recommandation)
        if not created:
            like.delete()  # Si le like existe déjà pour cet utilisateur et cette recommandation, le supprimer
        else:
            # Créez une notification associée à ce like
            Notification.objects.create(user=recommandation.user, like=like)
    return redirect('Student_Help:poste')

@login_required
def like_logement(request, logement_id):
    if request.method == 'POST':
        logement = get_object_or_404(Logement, pk=logement_id)
        like, created = Likelogement.objects.get_or_create(user=request.user, logement=logement)
        if not created:
            like.delete()  # Si le like existe déjà pour cet utilisateur et cette recommandation, le supprimer
        else:
            # Créez une notification associée à ce like
            Notificationl.objects.create(user=logement.user, like=like)
    return redirect('Student_Help:poste')


@login_required
def like_stage(request, stage_id):
    if request.method == 'POST':
        stage = get_object_or_404(Stage, pk=stage_id)
        like, created = LikeStage.objects.get_or_create(user=request.user, stage=stage)
        if not created:
            like.delete()  # Si le like existe déjà pour cet utilisateur et cette recommandation, le supprimer
        else:
            # Créez une notification associée à ce like
            Notifications.objects.create(user=stage.user, like=like)
    return redirect('Student_Help:poste')

@login_required
def like_transport(request, transport_id):
    if request.method == 'POST':
        transport = get_object_or_404(Transport, pk=transport_id)
        like, created = LikeTransport.objects.get_or_create(user=request.user, transport=transport)
        if not created:
            like.delete()  # Si le like existe déjà pour cet utilisateur et cette recommandation, le supprimer
        else:
            # Créez une notification associée à ce like
            Notificationt.objects.create(user=transport.user, like=like)
    return redirect('Student_Help:poste')

@login_required
def like_event(request, evenement_id):
    if request.method == 'POST':
        evenement = get_object_or_404(Evènement, pk=evenement_id)
        like, created = LikeEvent.objects.get_or_create(user=request.user, evenement=evenement)
        if not created:
            like.delete()  # Si le like existe déjà pour cet utilisateur et cette recommandation, le supprimer
        else:
            # Créez une notification associée à ce like
            Notificatione.objects.create(user=evenement.user, like=like)
    return redirect('Student_Help:poste')
# @login_required
# def like_recommandation(request, recommandation_id):
#     if request.method == 'POST':
#         recommandation = Recommandation.objects.get(pk=recommandation_id)
#         like, created = Like.objects.get_or_create(user=request.user, recommandation=recommandation)
#         if not created:
#             like.delete()  # Si le like existe déjà pour cet utilisateur et cette recommandation, le supprimer
#     return redirect('Student_Help:poste')

@login_required
def creer_commentaire(request, recommandation_id):
    recommendation = get_object_or_404(Recommandation, pk=recommandation_id)

    if request.method == 'POST':
        comment_text = request.POST.get('comment')
        if comment_text: 
            Commentaire.objects.create(
                user=request.user,
                recommandation=recommendation, 
                texte=comment_text
            )
            messages.success(request, 'Commentaire ajouté avec succès.')
           
            return redirect(reverse('Student_Help:list_comments', kwargs={'publication_id': recommandation_id}))
        else:
            messages.error(request, 'Le commentaire ne peut pas être vide.')
        
  
    return redirect(reverse('Student_Help:poste', kwargs={'recommandation_id': recommandation_id}))

@login_required
def creer_commentairel(request, logement_id):
    logement = get_object_or_404(Logement, pk=logement_id)

    if request.method == 'POST':
        comment_text = request.POST.get('comment')
        if comment_text:  # Check if comment is not empty
            comment = Commentairel.objects.create(
                user=request.user,
                logement=logement,  # Assign recommendation directly
                texte=comment_text
            )
            messages.success(request, 'Commentaire ajouté avec succès.')
        else:
            messages.error(request, 'Le commentaire ne peut pas être vide.')
        
        return render(request, 'student_help/list_posts.html', {'comment': logement})
    
    return render(request, 'student_help/list_posts.html', {'comment': logement})

Student_Help/templates/Student_Help/Modifier_comment.html
{% extends 'Student_Help/base.html' %}

{% block content %} 
<div class="container">
    <h1>Modifier  </h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Enregistrer les modifications</button>
    </form>
</div>
{% endblock %}

Student_Help/templates/Student_Help/Supprimer_fr.html
{% extends 'Student_Help/base.html' %}

{% block content %}
<div class="container">
    <h1>Supprimer</h1>
    <p>Êtes-vous sûr de vouloir supprimer cet ami ?</p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <button type="submit" class="btn btn-success">Confirmer la suppression</button>
    </form>
</div>
{% endblock %}

Student_Help/templates/Student_Help/Transport.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EBook</title>
    <link rel="stylesheet" href="{% static 'css/style6.css' %}">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <nav>

        <div class="left">

            <div class="logo">
                <img src="{{transport.user.image.url}}">
            </div>

            <div class="search_bar">

                <i class="fa-solid fa-magnifying-glass"></i>
                <input type="text" placeholder="Search EBook">

            </div>

        </div>

        <div class="center">
            <div class="publication-section">
                <form id="publication-form" method="post" action="">
                   {% csrf_token %}
                   <div class="form-group">
                </div>
                <a href="{% url 'Student_Help:ajoutTransport' %}"></a>
                <button type="submit" class="btn btn-primary" id="redirectButton"><i class='bx bxs-share' style='color:#f0e3e3' ></i></button>
                </form>
             </div>
            </div>
    </nav>
    <center>
        <div class="publication-section">
            <form id="publication-form" method="post" action="">
                {% csrf_token %}
                <div class="form-group">
                 <label for="type">Type de publication:</label>
                 <select class="form-control" id="type" name="type">
                    <option value="recommandation">Recommandation</option>
                    <option value="logement">Logement</option>
                    <option value="transport">Transport</option>
                    <option value="stage">Stage</option>
                    <option value="evenement">Événement</option>
                </select>
              </div>
              <button type="submit" class="btn btn-primary" id="redirectButton"><i class='bx bxs-share' style='color:#f0e3e3' ></i></button>
            </form>
        </div>
        <!------------main--------------->
        <div class="main">
        <div class="center">
            {% for transport in transports %}
            <div class="friends_post">
                <div class="friend_post_top">
                    <div class="img_and_name">
                        <img src="/media/{{ transport.user.image }}">
                        <div class="friends_name">
                            <p class="friends_name">
                                {{ transport.user.nom }} {{ transport.user.prenom }}
                            </p>
                            <p class="time">{{ transport.date }}
                            </p>
                        </div>
                    </div>
                    <div class="menu">
                        <i class="fa-solid fa-ellipsis"></i>
                    </div>
                </div>
                {% if transport.image %}
                <p>Heure de départ: {{ transport.heure_dep }}</p>
                <p>{{ transport.départ }} - {{ transport.destination }}</p>
                <h3>Nombre de sièges disponibles: {{ transport.nbre_siège }}</h3>
                <img src="{{ transport.image.url }}">
                {% endif %}
                <div class="info">
                    <div class="emoji_img">
                    </div>
                    <div class="comment">
                    </div>
                </div>
                <hr>
                <div class="like">
                    <div class="like_icon">
                        <button class="like-btn btn btn-primary" data-id="{{ transport.id }}" style="border: none;"><i class='bx bxs-like' style='color:#000000 ; '  ></i></button>
                    </div>
                    <div class="like_icon">
                        <button type="submit" class="btn btn-primary" data-id="{{ transport.id }}" style="border: none;"><i class='bx bx-message-rounded-dots' style='color:#000000'  ></i></button>
                    </div>
                </div>
                <hr>
                <div class="comment_warpper">
                    <img src=" {{transport.user.image.url}} ">
                    <div class="circle"></div>
                    <div class="comment_search">
                        <input type="text" placeholder="Write a comment">
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div> 
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        // Sélectionnez le bouton
        const button = document.getElementById('redirectButton');
    
        // Ajoutez un écouteur d'événements pour le clic sur le bouton
        button.addEventListener('click', function() {
            // Redirigez l'utilisateur vers l'URL spécifiée
            window.location.href = "{% url 'Student_Help:ajoutTransport' %}";
        });
    </script>
    <script>
       
       $(document).ready(function() {
     // Afficher/Masquer le champ de commentaire
     // Soumettre le formulaire de publication
     $('#publication-form').submit(function(event) {
       event.preventDefault();
       var form = $(this);
       var type = form.find('#type').val();
       if (type === 'recommandation') {
         window.location.href = "{% url 'Student_Help:ajoutRec' %}"; // Redirection vers la vue ajoutRec pour les recommandations
       } else if (type === 'logement') {
         window.location.href = "{% url 'Student_Help:ajoutLogement' %}"; // Redirection vers la vue ajoutLogement pour les logements
       } else if (type === 'stage') {
         window.location.href = "{% url 'Student_Help:ajoutStage' %}"; // Redirection vers la vue ajoutStage pour les stages
       }else if (type === 'evenement') {
         window.location.href = "{% url 'Student_Help:ajoutEvenement' %}"; // Redirection vers la vue ajoutStage pour les stages
       }else if (type === 'transport') {
         window.location.href = "{% url 'Student_Help:ajoutTransport' %}"; // Redirection vers la vue ajoutStage pour les stages
       }
     });})
   
    </script>
</body>
</html>

Student_Help/templates/Student_Help/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Student Help{% endblock %}</title>
    {% block styles %}
    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- custom css file link  -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+Knujsl5+z8w/D2bNajYaV8ND0Kr5+DIePbpfrVA6kEUthd" crossorigin="anonymous">

    {% endblock %}
</head>
<body>
    {% block body %}
<div class="container">

<header>

    <a href="{% url 'Student_Help:ind' %}" class="logo">Student<span>Help</span></a>

    <div id="menu" class="fas fa-bars"></div>

    <nav class="navbar">
        {% if user.is_authenticated %}
        <!-- <a href="{% url 'Student_Help:post'%}">Nouveautés</a> -->
        <a href="{% url 'Student_Help:notif'%}"><i class="fa-solid fa-bell"></i>Notifications</a>
        <a href="{% url 'Student_Help:inbox'%}"><i class="fa-solid fa-message"></i>Message</a>
        <a href="{% url 'Student_Help:contact'%}"><i class="fa-solid fa-address-book"></i>contact</a>
        <a href="{% url 'Student_Help:poste'%}"><i class="fa-solid fa-newspaper"></i>post</a>
        <a href="{% url 'Student_Help:invite_list'%}"><i class="fa-solid fa-user-plus"></i>add Friends</a>
        <a href="{% url 'Student_Help:invitation_list'%}"><i class="fa-solid fa-plus"></i>request</a>
        <a href="{% url 'Student_Help:view_friends'%}"><i class="fa-solid fa-user-group"></i>Amis</a>
        <a href="{% url 'Student_Help:edit_profile' %}" class="nav-link"><i class="fa-solid fa-user-pen"></i>Edit profile</a>
        <a class="nav-link" href="#">
            <a href="#" class="nav-link">
                <img src="{% if user.is_authenticated and user.photo %}{{ user.photo.url }}{% else %}{% static 'image/compte-utilisateur-1.png' %}{% endif %}" alt="Image de profil" class="profile-image" width="30px">{{ user }}
            </a>
            
        <a class="nav-link" href="{% url 'Student_Help:logout' %}">Déconnexion</a>
        {% else %}   
        <a href="{% url 'Student_Help:list_Enseignant'%}"><i class="fa-solid fa-chalkboard-user"></i>Enseignant</a>
        <a href="{% url 'Student_Help:plan'%}"><i class="fa-solid fa-school"></i>plan</a>
        <a href="{% url 'Student_Help:org'%}"><i class="fa-solid fa-school-flag"></i>Organigramme</a>
        <a href="{% url 'Student_Help:clubIset'%}"><i class="fa-solid fa-people-group"></i>Clubs</a>
        <a href="{% url 'jeu:home'%}"><i class="fa-solid fa-gamepad"></i>Jeu n°1</a>
        <a href="{% url 'game:index'%}"><i class="fa-solid fa-gamepad" style="color: #47246b;"></i>Jeu n°2</a>
        <a class="nav-link" href="{% url 'Student_Help:register' %}"><i class='bx bxs-face'></i>Inscription</a>
        <a class="nav-link" href="{% url 'Student_Help:login' %}"><i class='bx bx-log-in'></i>Se connecter</a> 
        

        {% endif %}     
    </nav>
    
    {% endblock %}
    <!-- <a href="{% url 'Student_Help:register' %}"></a>
    <a href="{% url 'login' %}"></a>  -->
    
</header>
{% block content %}{% endblock %}
<!-- home section  -->

<!-- <section class="home">

    <div class="content">
        <h3>nous créons cette plateforme pour aider les étudiants d'Iset SFAX</h3>
        <p>Pour découvrir notre institut voir cette galerie</p>
        <a href="galery.html" class="btn">Voir galerie</a>
    </div>

    <div class="image">
        <img src="images/home-img.svg" alt="">
    </div>

</section>
 -->

<!-- footer section  -->
{% block footer %}
<section class="footer">

    <div class="box-container">

    

        <!-- <div class="box">
            <h3>Liens rapides</h3>
            <a href="index.html">home</a>
            <a href="course.html">Nouveautés</a>
            <a href="teacher.html">Enseignant</a>
            <a href="contact.html">contact</a>
        </div> -->

        <div class="box">
            <h3>Suivez-nous</h3>
            <a href="#">facebook</a>
            <a href="#">Instagram</a>
        </div>

        <div class="box">
            <h3>Contactez-nous</h3>
           <p> <i class="fas fa-phone"></i> +123-456-7890 </p>
           <p> <i class="fas fa-envelope"></i> StudentHelp@gmail.com </p>
           <p> <i class="fas fa-map-marker-alt"></i>Route de Mahdia Km 2.5 BP 88 A - El Bustan , 3099 Sfax</p>
        </div>

    </div>

    <div class="credit"> créés par <span> Oumaima Feki & Chayma Mkaouar </span> |tous droits réservés</div>

</section>
{% endblock %}
</div>

<!-- custom js file link -->
<script src="{% static 'js/script.js' %}"></script>

</body>
</html>

Student_Help/templates/Student_Help/modifier_post.html
{% extends 'Student_Help/base.html' %}

{% block content %} 
<div class="container">
    <h1>Modifier  </h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Enregistrer les modifications</button>
    </form>
</div>
{% endblock %}